---
build pdf epub book:
  image: asciidoctor/docker-asciidoctor:1.14
  artifacts:
    expire_in: 7days
    paths:
      - build/PlantUML.pdf
      - build/PlantUML.epub
  allow_failure: true
  script:
    - asciidoctor-pdf --require asciidoctor-diagram
                      --attribute sourcedir=../../../../../assets/
                      --destination-dir build
                      PlantUML.adoc
    - asciidoctor-epub3 --require asciidoctor-diagram
                        --attribute sourcedir=../../../../../assets/
                        --destination-dir build
                        PlantUML.adoc

pages:
  stage: deploy
  image: alpine:3.15
  needs: []
  before_script:
    - apk update
    - apk add openssl git tzdata asciidoctor nodejs npm hugo

    - find content -name "*.adoc" -type f -exec sed -i 's/\[plantuml/\[source, plantuml/' {} +
    - find content -name "*.adoc" -type f -exec sed -i '/\/\/\/\//d' {} +
    - find content -name "*.md" -type f -exec sed -i '/<!---md/d' {} +
    - find content -name "*.md" -type f -exec sed -i '/md--->/d' {} +

    - npm install

    - git submodule update --init --recursive

  script:
    - hugo --gc --destination ./public --baseURL ${PAGES_BASE_URL}
  artifacts:
    paths:
    - public
  only:
  - main
