---
build pdf book:
  image: asciidoctor/docker-asciidoctor:1.12
  artifacts:
    expire_in: 7days
    paths:
      - build/PlantUML.pdf
  script:
    - asciidoctor-pdf --require asciidoctor-diagram
                      --destination-dir build
                      --out-file PlantUML.pdf
                      PlantUML.adoc
pages:
  stage: deploy
  image: alpine:3.14
  before_script:
    - apk update
    - apk add openssl git tzdata asciidoctor nodejs npm hugo

    - cp assets/*.puml portal/assets

    - cp PlantUML-c4model.adoc portal/content/en/docs/
    - cp PlantUML-samples.adoc portal/content/en/docs/

    - find portal/content -name "*.adoc" -type f -exec sed -i 's/\[plantuml/\[source, plantuml/' {} +
    - find portal/content -name "*.adoc" -type f -exec sed -i '/\/\/\/\//d' {} +

    - cd portal

    - npm install

    - git submodule update --init --recursive

  script:
    - hugo --gc --destination ../public --baseURL ${PAGES_BASE_URL}
  artifacts:
    paths:
    - public
  only:
  - main
