= PlantUML demo

This repo demonstrate how to generate document formating by using
markdown{wj}footnote:[Markdown: https://en.wikipedia.org/wiki/Markdown[]] or
AsciiDoc{wj}footnote:[AsciiDoc: https://en.wikipedia.org/wiki/AsciiDoc[]]
documents that has PlantUML diagrams - upstream repo on
Gitlab.com{wj}footnote:[PlantUML demo (upstream repo): https://gitlab.com/adrianovieira/plantuml-demo[]].

> _PlantUML is a component that allows to quickly write both UML or non-UML diagrams_ - https://plantuml.com[PlantUML.com]

== Getting started

=== Simple sample files

* Markdown: link:content/en/docs/modeling/uml/PlantUML.md[]
* AsciiDoc sections:
  ** main: link:PlantUML.adoc[]
  ** UML Sequence diagram: link:content/en/docs/modeling/uml/PlantUML-samples.adoc[PlantUML-samples]
  ** C4Model diagram: link:content/en/docs/modeling/c4model/PlantUML-c4model.adoc[PlantUML-c4model]

=== Pages

A sample portal is deployed at https://adrianovieira.gitlab.io/plantuml-demo

Tecnologies::
* Hugo-0.83+{wj}footnote:[Hugo: https://gohugo.io[]]: A static site generator
* Docsy theme{wj}footnote:[Docsy: https://www.docsy.dev[]]: A Hugo theme for creating great technical documentation sites

Requirements::
* git submodule update: if you wanna give it a try locally
+
[source, bash]
----
$ git submodule update --init --recursive
$ cd portal

$ # before you run the command bellow,
$ # take a look in pages job on .gitlab-ci.yml to check how to update portal/content
$ hugo server
----

=== AsciiDoc artifacts

.Install Asciidoctor
[source, bash]
----
$ [sudo] gem install asciidoctor asciidoctor-diagram asciidoctor-pdf \
                     asciidoctor-diagram-plantuml asciidoctor-epub3
----

.Install GraphViz
[source, bash]
----
$ sudo dnf|apt install -y graphviz
----

.Generate pdf book
[source, bash]
----
$ asciidoctor-pdf PlantUML.adoc \
                  -a sourcedir=../../../../../assets/ \
                  -r asciidoctor-diagram \
                  -D build
----

.Generate epub book
[source, bash]
----
$ asciidoctor-epub3 PlantUML.adoc \
                  -a sourcedir=../../../../../assets/ \
                  -r asciidoctor-diagram \
                  -D build
----

.Open generated files
[source, bash]
----
build
├── PlantUML.epub
└── PlantUML.pdf
----
