---
name: Generate pdf and epub book files
on: push

jobs:
  build:
    name: build pdf and epub books
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:1.12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build pdf book file
        run: |
          asciidoctor-pdf --require asciidoctor-diagram \
                  --attribute sourcedir=../../../../../assets/ \
                  --destination-dir build \
                  PlantUML.adoc
      - name: build epub book file
        run: |
          asciidoctor-epub3 --require asciidoctor-diagram \
                              --attribute sourcedir=../../../../../assets/ \
                              --destination-dir build \
                              PlantUML.adoc
      - name: Upload pdf file
        uses: actions/upload-artifact@v2
        with:
          name: PlantUML book
          path: |
            build/PlantUML.pdf
            build/PlantUML.epub
