---
name: Generate pdf book file
on: push

jobs:
  build:
    name: build pdf book
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:1.12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build pdf book file
        run: |
          asciidoctor-pdf --require asciidoctor-diagram \
                            --destination-dir build \
                            --out-file PlantUML.pdf \
                            PlantUML.adoc
          asciidoctor-epub3 --require asciidoctor-diagram \
                              --destination-dir build \
                              PlantUML.adoc
      - name: Upload pdf file
        uses: actions/upload-artifact@v2
        with:
          name: PlantUML book
          path: |
            build/PlantUML.pdf
            build/PlantUML.epub
