name: generate github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy github pages
    runs-on: ubuntu-latest
    container: alpine:3.15
    steps:
      - uses: actions/checkout@v2

      - name: update git submodules
        run: git submodule update --init --recursive

      - name: Install alpine packages
        run: |
          apk update
          apk add openssl git asciidoctor nodejs npm hugo

      - name: Install node modules
        run: |
          npm install

      - name: Prepare docs to build pages
        run: |
          find content -name "*.adoc" -type f -exec sed -i 's/\[plantuml/\[source, plantuml/' {} +
          find content -name "*.adoc" -type f -exec sed -i '/\/\/\/\//d' {} +
          find content -name "*.md" -type f -exec sed -i '/<!---md/d' {} +
          find content -name "*.md" -type f -exec sed -i '/md--->/d' {} +

      - name: Build portal
        run: hugo --minify

      - name: Deploy portal
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public