name: generate github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy github pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: install ubuntu extra packages
        run: |
          sudo apt-get -q update
          sudo apt-get install --quiet --assume-yes asciidoctor

      - name: update git submodules
        run: |
          git submodule update --init --recursive

      - name: install node modules
        run: |
          npm install

      - name: prepare asciidoc documents
        run: |
          find content -name "*.adoc" -type f -exec sed -i 's/\[plantuml/\[source, plantuml/' {} +
          find content -name "*.adoc" -type f -exec sed -i '/\/\/\/\//d' {} +
          find content -name "*.md" -type f -exec sed -i '/<!---md/d' {} +
          find content -name "*.md" -type f -exec sed -i '/md--->/d' {} +
          
      - name: Build
        run: hugo --minify --baseURL ${{secrets.PAGES_BASE_URL}}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public